// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA8P1reeANqyexm7plDpgLN9re4oBhG9g',
    appId: '1:1044105916142:web:ed329db44f249171b6cdff',
    messagingSenderId: '1044105916142',
    projectId: 'firebase-database-project',
    authDomain: 'fir-database-project-3561b.firebaseapp.com',
    storageBucket: 'firebase-database-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1SnpEVxe_PFPW-N8LwPb7dO88JGPqR-k',
    appId: '1:1044105916142:android:1f9e1f4d5cc6bd3eb6cdff',
    messagingSenderId: '1044105916142',
    projectId: 'firebase-database-project',
    storageBucket: 'firebase-database-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDLHUKV1xUcKq-zUwufkZDvMKfwXQ4dkg',
    appId: '1:1044105916142:ios:d463901dd6b6366eb6cdff',
    messagingSenderId: '1044105916142',
    projectId: 'firebase-database-project',
    storageBucket: 'firebase-database-project.appspot.com',
    iosClientId: '1044105916142-esrd6gt3nmq41k943j0q0kl9p7vi325f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFirestoreDatabaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDLHUKV1xUcKq-zUwufkZDvMKfwXQ4dkg',
    appId: '1:1044105916142:ios:d463901dd6b6366eb6cdff',
    messagingSenderId: '1044105916142',
    projectId: 'firebase-database-project',
    storageBucket: 'firebase-database-project.appspot.com',
    iosClientId: '1044105916142-esrd6gt3nmq41k943j0q0kl9p7vi325f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFirestoreDatabaseProject',
  );
}
